name: CI/CD for Railway

on:
  push:
    branches:
      - main  # Jalankan workflow setiap push ke branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Railway
        uses: railwayapp/cli-action@v1
        with:
          service: ${{ secrets.RAILWAY_SERVICE_ID_PROD }}
          token: ${{ secrets.RAILWAY_PROD_TOKEN }}
